backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use app\models\LoginForm;
use yii\web\UploadedFile;
use backend\models\PasswordForm;
use backend\models\PasswordResetRequestForm;
use backend\models\ResetPasswordForm;

/**
* Site controller
*/
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error', 'permission','changepassword', 'profile', 'edit-profile','request-password-reset','reset-password'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                   
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }
   

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        $login = new \app\models\LoginDetails();

        if ($model->load(Yii::$app->request->post()) ) {
            $log = \app\models\User::find()->where(['username' => $_POST['LoginForm']['username'], 'status' => 1])->andWhere(['<>','user_type', 2])->one();

           // print_r($_POST['LoginForm']['username']);die;
            if(empty($log)) {
                \Yii::$app->session->setFlash('loginError', '<i class="fa fa-warning"></i><b> Incorrect username or password. !</b>');
                return $this->render('login', ['model' => $model]);
            }
            $login->login_user_id = $log['id'];
            $login->login_status = 1;
            $login->login_at = new \yii\db\Expression('NOW()');
            $login->user_ip_address=$_SERVER['REMOTE_ADDR'];
            $login->save(false);
            if($model->login()) {
                return $this->goBack();
            }
            else
                return $this->render('login', ['model' => $model,]);
        } else {
            $model->password = '';

            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {

        if(isset(Yii::$app->user->id))
        \app\models\LoginDetails::updateAll(['login_status' => 0, 'logout_at'=> new \yii\db\Expression('NOW()')],'login_user_id='.Yii::$app->user->id.' AND login_status = 1');
        Yii::$app->user->logout();
        return $this->redirect(['login']);

        //return $this->goHome();
    }
    public function actionPermission()
    {
          return $this->render('denied');
    }
     public function actionProfile($id)
    {
        $model = \app\models\User::findOne($id);

        return $this->render('profile',[
                    'model'=>$model
                ]);
    }
    public function actionEditProfile($id)
    {
        $model = \backend\models\Users::findOne($id);
        $image=$model->profile_pic;
        if ($model->load(Yii::$app->request->post()))
             {
                 $model->birth_date=date("Y-m-d",strtotime($model->birth_date));
                 $model->username=$model->email;
                 $model->profile_pic = UploadedFile::getInstance($model, 'profile_pic');
            if($model->profile_pic=="")
            {
                $model->profile_pic=$image;
            }
            else
            {
                if ($model->profile_pic && $model->validate()) {                
                    $model->profile_pic->saveAs('profile/' . $model->profile_pic->baseName . '.' . $model->profile_pic->extension, false);
                    $filepath=Yii::$app->params['server']."profile/". $model->profile_pic;
                    $model->profile_pic= $filepath;
                }
            }
            if($model->save())
            {
                Yii::$app->session->setFlash('success', "Profile updated successfully."); 
                return $this->redirect(['profile', 'id'=>$id]);
            }
        }
        return $this->render('edit_profile',[
                    'model'=>$model
                ]);
    }
public function actionRequestPasswordReset()
    {
        $this->layout = '/../layouts/main-login';
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');
               // return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }
        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    
    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        $this->layout = '/../layouts/main-login';
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidArgumentException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');
            return $this->goHome();
        }
        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    public function actionChangepassword(){

        $model = new PasswordForm;
        $modeluser = \backend\models\Users::find()->where([
            'username'=>Yii::$app->user->identity->username
        ])->one();
        
        if($model->load(Yii::$app->request->post())){
            if($model->validate()){
                try{
                    $modeluser->password = sha1($_POST['PasswordForm']['newpass']);
                    if($modeluser->save()){
                    require '../../vendor/autoload.php'; 
                    $email = new \SendGrid\Mail\Mail(); 
                        $content='<div style="font:18px/23px Arial,Helvetica,sans-serif;background:#f3f3f3">
                 <div style="max-width:800px;margin-left:auto;margin-right:auto">
                    <div style="width:640px;margin-left:auto;margin-right:auto;padding:20px 0px 20px 0px; style="text-align: center;">
                        <table class="x_-665217761MsoNormalTable" border="1" cellspacing="3" cellpadding="0" style="border: solid rgb(204,204,204) 1.0pt;background: #fff;color: #000;width:98%">
                      <tbody>
                        <tr>
                          <td style="border: none;padding: 5.25pt 22.5pt 5.5pt 22.5pt;">
                          <h2 align="center" style="text-align: center;font-family: Helvetica;">Change Password</h2>
                          <p class="MsoNormal" align="center" style="text-align: center;font-family: Helvetica;"><span style="font-size: 10.0pt;">Your password for VWA changed successfully. New login details: </span></p>                        
                          
                          </td>
                        </tr>
                       
                        <tr>
                          <td style="border: none;padding: 5.25pt 22.5pt 5.5pt 22.5pt;">
                           <p class="MsoNormal" align="center" style="text-align: left;font-family: Helvetica;"><span style="font-size: 10.0pt;"><b>Username: </b>'.$modeluser->username.'</span></p>
                          </td>
                        </tr>
                         <tr>
                          <td style="border: none;padding: 5.25pt 22.5pt 5.5pt 22.5pt;">
                           <p class="MsoNormal" align="center" style="text-align: left;font-family: Helvetica;"><span style="font-size: 10.0pt;"><b>Password: </b>'.$_POST['PasswordForm']['newpass'].'</span></p>
                          </td>
                        </tr>
                        <tr>
                          <td style="border: none;padding: 5.25pt 22.5pt 5.5pt 22.5pt;">
                          <p class="MsoNormal" align="center" style="font-family: Helvetica;text-align: center;"><span style="font-size: 10.0pt;font-family: Helvetica;">Thank You</span></p></td>
                        </tr>
                      </tbody>
                    </table> 
                    </div>
                 </div>
              </div>';
                $email->setFrom("info@vishwaswealthadvisory.com","Vishwas Wealth Advisory");
                $email->setSubject('Change Password - Vishwas Wealth Advisory' );
                $email->addTo($modeluser->email);
                $email->addContent(
                    "text/html", $content
                );
                $sendgrid = new \SendGrid(Yii::$app->params['SENDGRID_API_KEY']);
                        try {
                            $response = $sendgrid->send($email);

backend/views/site/changepassword.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Change Password';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="box box-primary">
    <div class="box-body"> 
<div class="site-changepassword">   
    <p>Please fill out the following fields to change password :</p>
   
    <?php $form = ActiveForm::begin([
        'id'=>'changepassword-form',
        'options'=>['class'=>'form-horizontal'],
        'fieldConfig'=>[
            'template'=>"{label}\n<div class=\"col-lg-3\">
                        {input}</div>\n<div class=\"col-lg-5\">
                        {error}</div>",
            'labelOptions'=>['class'=>'col-lg-2 control-label'],
        ],
    ]); ?>
        <?= $form->field($model,'oldpass',['inputOptions'=>[
            'placeholder'=>'Old Password'
        ]])->passwordInput() ?>
       
        <?= $form->field($model,'newpass',['inputOptions'=>[
            'placeholder'=>'New Password'
        ]])->passwordInput() ?>
       
        <?= $form->field($model,'repeatnewpass',['inputOptions'=>[
            'placeholder'=>'Repeat New Password'
        ]])->passwordInput() ?>
       
        <div class="form-group">
            <div class="col-lg-offset-2 col-lg-11">
                <?= Html::submitButton('Change password',[
                    'class'=>'btn btn-primary'
                ]) ?>
            </div>
        </div>
    <?php ActiveForm::end(); ?>
</div>
</div>
</div>

backend/views/site/denied.php
<?php 
	$this->title = 'Access Denied';

?>
<div class="site-error">

    <div class="alert alert-danger">
        <span class="fa fa-warning"></span> Access is denied!
    </div>

    <p>
        You don't have permission to access this module.
    </p>
    <p>
        Please refer to your system administrator. Thank you.
    </p>

</div>

backend/views/site/edit_profile.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use backend\models\RoleMaster;
use yii\helpers\Url;
use kartik\date\DatePicker;
$model->birth_date=date("d-M-Y",strtotime($model->birth_date));
/* @var $this yii\web\View */
/* @var $model backend\models\Role */
/* @var $form yii\widgets\ActiveForm */
if( \Yii::$app->session->hasFlash('msg'))
        echo \Yii::$app->session->getFlash('msg');
?>
<div class="role-form">
    <div class="box box-primary">
        <div class="box-body">
    <?php $form = ActiveForm::begin(['enableClientValidation' => false]); ?>
    <div class="row">
     <div class="col-md-4">       

                 <?php
                 $roles=RoleMaster::find()->where(['status' => 1])->all();
                $listData=ArrayHelper::map($roles,'role_id','role_name');
             echo $form->field($model, 'user_type')->widget(Select2::classname(), [
                    'data' => $listData,
                    'options' => ['placeholder' => '-- Select --'],
                    'pluginOptions' => [
                        'allowClear' => true
                    ],
                ]) ;?>
        </div>
  
      <div class="col-md-4">
                <?= $form->field($model, 'first_name')->textInput(['maxlength' => true]) ?>
      </div>
      <div class="col-md-4">
                <?= $form->field($model, 'last_name')->textInput(['maxlength' => true]) ?>
      </div>
      <div class="col-md-4">
        <?= $form->field($model, 'email')->textInput(['maxlength' => true,'onfocusout'=>"checkUser()();",'readonly'=>true]) ?>
      </div>
      <div class="col-md-4">
                <?= $form->field($model, 'mobile')->textInput(['maxlength' => true]) ?>
      </div> 
       <div class="col-md-4">
                <?= $form->field($model, 'city')->textInput(['maxlength' => true]) ?>
      </div>      
      
      <div class="col-md-4 radiobtn">
                    <?php $list = ["1"=>"Male", "2"=>"Female"];
                    echo $form->field($model, 'gender')->radioList($list); ?>
                </div> 
       
      <div class="col-md-4">
        <label>Date Of Birth</label>
                    <?= DatePicker::widget([
                                'model'=>$model,
                                'attribute' => 'birth_date',
                                'value' => date('d-M-Y', strtotime('+2 days')),
                                'options' => ['placeholder' => 'Select date ...'],
                                'pluginOptions' => [
                                    'format' => 'dd-M-yyyy',
                                    'todayHighlight' => true
                                ]
                            ]); ?>
                </div>
           <div class="col-md-4">
                <?= $form->field($model, 'profile_pic')->fileInput() ?>
            </div>
            
                <?php
                if($model['profile_pic']!=""){
                    echo "<div class='col-md-4'>";
                    echo "<label>Uploaded Profile Pic</label>";
                 echo "<img src='".$model->profile_pic."' class='profile-user-img role-name img-responsive img-circle' onerror='this.src=\"".Yii::$app->params['image']."images/user.jpg\"'  alt='image' style='height:75px'>";
                 echo "</div>";
                }
           ?>
      
</div>
       <div class="form-group text-center">
            <?= Html::submitButton(Yii::t('app', 'Save'), ['class' => 'btn btn-success mt-2-2']) ?>
       </div>
 
<?php ActiveForm::end(); ?>

</div>
</div>
</div>

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/forgotpassword.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

$this->title = 'Forgot Password';

?>

<div class="login-box">
    <div class="login-logo">
        <a href="#"><img src="<?= Yii::$app->params['logo']?>" /></a>
    </div>
    <!-- /.login-logo -->
    <div id="om-lightbox-case-study-optin-bar" class="boston-clearfix boston-optin-bar om-clearfix"><span class="boston-bar boston-yellow-bar om-bar om-red-bar"></span><span class="boston-bar boston-black-bar om-bar om-blue-bar"></span><span class="boston-bar boston-yellow-bar om-bar om-red-bar"></span><span class="boston-bar boston-black-bar om-bar om-blue-bar"></span></div>
    <div class="login-box-body">
        <p class="login-box-msg">Sign in to start your session</p>

        <?php $form = ActiveForm::begin(['id' => 'login-form', 'enableClientValidation' => false]); ?>

        <?= $form->field($model,'username',['inputOptions'=>[
            'placeholder'=>'Username'
        ]])->textInput() ?>
       
        <?= $form->field($model,'newpass',['inputOptions'=>[
            'placeholder'=>'New Password'
        ]])->passwordInput() ?>
       
        <?= $form->field($model,'repeatnewpass',['inputOptions'=>[
            'placeholder'=>'Repeat New Password'
        ]])->passwordInput() ?>

        <div class="row">
           
            <div class="col-xs-12">
                <?= Html::submitButton('Submit', ['class' => 'btn btn-primary btn-block btn-flat', 'name' => 'login-button']) ?>
                <?= Html::a(
                                    'Back to login',
                                    ['site/login'],
                                    ['class' => 'btn btn-primary btn-block btn-flat']
                                ) ?>
            </div>
            <!-- /.col -->
        </div>

        <?php ActiveForm::end(); ?>
         
    </div>
    <!-- /.login-box-body -->
</div><!-- /.login-box -->
<style type="text/css">
    .login-page, .register-page {
    height: auto;
    background: #d2d6de;
    display: block;
    position: fixed;
    top: 0;
    left: 0;
    height: 100%;
    width: 100%;
    background: url(<?= Yii::$app->params['image']?>images/bg.png) transparent;
    background-size: auto 100%;
    z-index: -1;
}
.btn-primary {
    background-color: #e7a54f!important;
    border-color: #e7a54f!important;
}
.btn-primary:hover {
    background-color: #fff!important;
    border-color: #e7a54f!important;
    color: #e7a54f;
}
.boston-optin-bar {
    margin-bottom: 20px;
}
.boston-yellow-bar {
    background-color: #e7a54f;
}
.boston-bar {
    float: left;
    width: 25%;
    height: 11px;
    display: block;
}
.boston-black-bar {
    background-color: #191919;
}
</style>

backend/views/site/index.php
<?php
use backend\models\Vehicles;
use backend\models\Company;
use backend\models\Transporter;
use yii\helpers\Html;
use yii\helpers\Url;

/* @var $this yii\web\View */
$this->title = 'Dashboard';
?>

<div class="site-index">
  
</div>
 

backend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-login">
   
    <p>Please fill out the following fields to login:</p>

    <div class="row">
        <div class="col-lg-5">
            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

                <?= $form->field($model, 'username')->textInput(['autofocus' => true]) ?>

                <?= $form->field($model, 'password')->passwordInput() ?>

                <?= $form->field($model, 'rememberMe')->checkbox() ?>

                <div class="form-group">
                    <?= Html::submitButton('Login', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
                </div>

            <?php ActiveForm::end(); ?>
        </div>
    </div>
    <!-- Login -->
    <section class="overflow-hidden">
      <div class="row no-gutters">
        <div class="col-lg-6">
          <!-- Promo Block - Slider -->
          <div class="js-carousel h-100" data-autoplay="true" data-infinite="true" data-fade="true" data-speed="5000">
            <div class="js-slide g-bg-size-cover h-100 g-min-height-50vh" style="background-image: url(<?= Yii::$app->params['basepath'];?>images/1.jpg);" data-calc-target="#js-header"></div>

            <div class="js-slide g-bg-size-cover h-100 g-min-height-50vh" style="background-image: url(<?= Yii::$app->params['basepath'];?>images/2.jpg);" data-calc-target="#js-header"></div>
          </div>
          <!-- End Promo Block - Slider -->
        </div>

        <div class="col-lg-6">
          <div class="g-pa-50 g-mx-70--xl">
            <!-- Form -->
            <form class="g-py-15">
              <h2 class="h3 g-color-black mb-4">Start your free trial</h2>

              <div class="mb-4">
                <div class="input-group g-brd-primary--focus">
                  <div class="input-group-prepend">
                    <span class="input-group-text g-width-45 g-brd-right-none g-brd-gray-light-v4 g-color-primary"><i class="icon-finance-067 u-line-icon-pro g-pos-rel g-top-2"></i></span>
                  </div>
                  <input class="form-control g-color-black g-brd-left-none g-bg-white g-brd-gray-light-v4 g-pl-0 g-pr-15 g-py-15" type="email" placeholder="Username">
                </div>
              </div>

              <div class="mb-4">
                <div class="input-group g-brd-primary--focus">
                  <div class="input-group-prepend">
                    <span class="input-group-text g-width-45 g-brd-right-none g-brd-gray-light-v4 g-color-primary"><i class="icon-media-094 u-line-icon-pro g-pos-rel g-top-2"></i></span>
                  </div>
                  <input class="form-control g-color-black g-brd-left-none g-bg-white g-brd-gray-light-v4 g-pl-0 g-pr-15 g-py-15" type="password" placeholder="Password">
                </div>
              </div>

              <div class="row justify-content-between mb-4">
                <div class="col align-self-center">
                  <label class="form-check-inline u-check g-pl-25 mb-0">
                    <input class="g-hidden-xs-up g-pos-abs g-top-0 g-left-0" type="checkbox">
                    <div class="u-check-icon-checkbox-v6 g-absolute-centered--y g-left-0">
                      <i class="fa g-rounded-2" data-check-icon="&#xf00c"></i>
                    </div>
                    Keep signed in
                  </label>
                </div>
                <div class="col align-self-center text-right">
                  <a class="g-color-gray-dark-v4 g-color-primary--hover" href="#">Forgot password?</a>
                </div>
              </div>

              <div class="g-mb-50">
                <button class="btn btn-md btn-block u-btn-primary rounded text-uppercase g-py-13" type="button">Login</button>
              </div>

              <div class="text-center g-pos-rel pb-2 g-mb-50">
                <div class="d-inline-block g-width-200 g-height-1 g-bg-gray-light-v4"></div>
                <span class="u-icon-v2 u-icon-size--lg g-brd-gray-light-v4 g-color-gray-dark-v4 g-bg-white g-font-size-default rounded-circle text-uppercase g-absolute-centered g-pa-24">OR</span>
              </div>

              <div class="row justify-content-between no-gutters mb-4">
                <div class="col-6 text-right">
                  <button class="btn u-btn-outline-facebook rounded text-uppercase g-py-13 g-px-30 mr-1" type="button">
                    <i class="mr-1 fa fa-facebook"></i>
                    Facebook
                  </button>
                </div>
                <div class="col-6">
                  <button class="btn u-btn-outline-twitter rounded text-uppercase g-py-13 g-px-30 ml-1" type="button">
                    <i class="mr-1 fa fa-twitter"></i>
                    Twitter
                  </button>
                </div>
              </div>

              <p class="g-font-size-13 text-center mb-0">Don't have an account? <a class="g-font-weight-600" href="page-signup-11.html">signup</a>
              </p>
            </form>
            <!-- End Form -->
          </div>
        </div>
      </div>
    </section>
    <!-- End Login -->
</div>

backend/views/site/profile.php
<?php
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use backend\models\RoleMaster;

$this->title = 'Profile';
$this->params['breadcrumbs'][] = $this->title;
function getRole($role_id)
{

    $role="";
    $Role=RoleMaster::findOne($role_id);
    if($Role!="")
        $role=$Role->role_name;
    return $role;
}
?>
<div class="row gutters-sm">
  <div class="col-md-4 mb-3">
    <div class="card">
      <div class="card-body">
        <div class="d-flex flex-column align-items-center text-center">
          <?php if($model->profile_pic=="" && $model->profile_pic==null) {
            echo '<img src="'.Yii::$app->params['image'].'images/user.jpg" alt="Admin" class="rounded-circle" width="150">';
            }
            else
              {
                echo '<img src="'.$model->profile_pic.'" alt="Admin" class="rounded-circle" width="150">';
              }?>
          <div class="mt-3">
            <h4><?= $model->first_name?></h4>
            <p class="text-secondary mb-1"><?= getRole($model->user_type)?></p><br />
             <a class="btn btn-primary" href="<?= \yii\helpers\Url::to(['site/edit-profile','id'=>Yii::$app->user->identity->id])?>"><i class="fa fa-pencil"></i> Edit Profile</a>
          </div>
        </div>
      </div>
    </div>
   
  </div>
  <div class="col-md-8">
    <div class="card mb-3">
      <div class="card-body">
        <div class="row">
          <div class="col-sm-3">
            <h6 class="mb-0">Full Name</h6>
          </div>
          <div class="col-sm-9 text-secondary">
            <?= $model->first_name?> <?= $model->last_name?>
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <h6 class="mb-0">Email</h6>
          </div>
          <div class="col-sm-9 text-secondary">
            <?= $model->email?>
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <h6 class="mb-0">Mobile</h6>
          </div>
          <div class="col-sm-9 text-secondary">
            <?= $model->mobile;?>
          </div>
        </div>
        <hr>
         <div class="row">
          <div class="col-sm-3">
            <h6 class="mb-0">City</h6>
          </div>
          <div class="col-sm-9 text-secondary">
            <?= $model->city;?>
          </div>
        </div>
        <hr>
         <div class="row">
          <div class="col-sm-3">
            <h6 class="mb-0">Gender</h6>
          </div>
          <div class="col-sm-9 text-secondary">
           <?= ($model->gender==1)?"Male":"Female"; ?>
          </div>
        </div>
        <hr>
        <div class="row">
          <div class="col-sm-3">
            <h6 class="mb-0">Birth Date</h6>
          </div>
          <div class="col-sm-9 text-secondary">
            <?= (!empty($model->birth_date))?date_format(date_create($model->birth_date),'d-m-Y'): "Not set";?>
          </div>
        </div>
        <hr>
        
        
      </div>
    </div>
  </div>
</div>
       

<style type="text/css">
  .nav{display:block;}

</style>

backend/views/site/requestPasswordResetToken.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \frontend\models\PasswordResetRequestForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;

$this->title = 'Reset your password';
//$this->params['breadcrumbs'][] = $this->title;
?>
<div class="site-request-password-reset">
    <main id="page-main" role="main">
        <div class="container">
           <a id="main-content" tabindex="-1"></a>
           <div class="row">
              <div class="col-lg-12">
                 <div id="page-content">
                    <div class="content">
                       <div>
                          <div id="block-shelley-local-tasks" class="block">
                             <ul class="nav nav-tabs my-3">
                                <li class="nav-item"><a href="<?= yii\helpers\Url::to(["site/login"])?>" class="nav-link">Log in</a></li>                                
                                <li class="nav-item"><a href="<?= yii\helpers\Url::to(["site/request-password-reset"])?>" class="nav-link active is-active">Reset Your Password<span class="visually-hidden"></span></a></li>
                             </ul>
                          </div>
                          <?php if (Yii::$app->session->hasFlash('success')): ?>
                              <div class="alert alert-success alert-dismissable">
                                   <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                                   <?= Yii::$app->session->getFlash('success') ?>
                              </div>
                          <?php endif; ?>

                          <?php if (Yii::$app->session->hasFlash('error')): ?>
                              <div class="alert alert-danger alert-dismissable">
                                   <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                                   <h4><i class="icon fa fa-close"></i>Error!</h4>
                                   <?= Yii::$app->session->getFlash('error') ?>
                              </div>
                          <?php endif; ?>
                          <div class="mt-3 mb-3">
                          <div id="block-pagetitle" class="block  ">
                             <h1><?= $this->title; ?></h1>
                          </div>
                          <?php $form = ActiveForm::begin(['id' => 'request-password-reset-form']); ?>
                             <div class="form-group js-form-item form-item js-form-type-textfield form-item-name js-form-item-name">
                                
                                <?= $form->field($model, 'email')->textInput(['autofocus' => true]) ?>
                             </div>
                             <p>Password reset instructions will be sent to your registered email address.</p>
                             
                             <div data-drupal-selector="edit-actions" class="form-actions js-form-wrapper form-wrapper" id="edit-actions"><?= Html::submitButton('Submit', ['class' => 'btn btn-primary']) ?></div>
                          <?php ActiveForm::end(); ?>
                       </div>
                       </div>
                    </div>
                 </div>
              </div>
           </div>
        </div>
    </main>
</div>

backend/views/site/youtube.php
<?php
echo "<pre>"
print_r($videolist);
echo "</pre>";
?>