backend/models/User.php
<?php

namespace app\models;

use Yii;
use yii\base\NotSupportedException;
use yii\db\ActiveRecord;
use yii\helpers\Security;
use yii\web\IdentityInterface;

/**
 * This is the model class for table "{{%user}}".
 *
 * @property int $id
 * @property string $username
 * @property string $password
 * @property int $status
 */
class User extends \yii\db\ActiveRecord implements IdentityInterface
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['username', 'password'], 'required'],
            [['status'], 'integer'],
            [['username', 'password'], 'string', 'max' => 100],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'username' => 'Username',
            'password' => 'Password',
            'status' => 'Status',
        ];
    }

    /**
     * {@inheritdoc}
     * @return UserQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new UserQuery(get_called_class());
    }


    public static function findIdentity($id)
    {
        return static::findOne($id);
    }

    /**
     * @inheritdoc
     */
/* modified */
    public static function findIdentityByAccessToken($token, $type = null)
    {
          return static::findOne(['access_token' => $token]);
    }
 
/* removed
    public static function findIdentityByAccessToken($token)
    {
        throw new NotSupportedException('"findIdentityByAccessToken" is not implemented.');
    }
*/
    /**
     * Finds user by username
     *
     * @param  string      $username
     * @return static|null
     */
    public static function findByUsername($username)
    {
        return static::findOne(['username' => $username]);
    }

   
    /**
     * Finds user by password reset token
     *
     * @param  string      $token password reset token
     * @return static|null
     */
    public static function findByPasswordResetToken($token)
    {
        $expire = \Yii::$app->params['user.passwordResetTokenExpire'];
        $parts = explode('_', $token);
        $timestamp = (int) end($parts);
        if ($timestamp + $expire < time()) {
            // token expired
            return null;
        }

        return static::findOne([
            'password_reset_token' => $token
        ]);
    }

    /**
     * @inheritdoc
     */
    public function getId()
    {
        return $this->getPrimaryKey();
    }

    /**
     * @inheritdoc
     */
    public function getAuthKey()
    {
        return $this->auth_key;
    }

    /**
     * @inheritdoc
     */
    public function validateAuthKey($authKey)
    {
        return $this->getAuthKey() === $authKey;
    }

    /**
     * Validates password
     *
     * @param  string  $password password to validate
     * @return boolean if password provided is valid for current user
     */
    public function validatePassword($password)
    {
        return trim($this->password) === sha1($password);

        //return $this->password === sha1($password);
    }

    /**
     * Generates password hash from password and sets it to the model
     *
     * @param string $password
     */
    public function setPassword($password)
    {
        $this->password = SHA1($password);//Security::generatePasswordHash($password);
    }

    /**
     * Generates "remember me" authentication key
     */
    public function generateAuthKey()
    {
        $this->auth_key = Security::generateRandomKey();
    }

    /**
     * Generates new password reset token
     */
    public function generatePasswordResetToken()
    {
        $this->password_reset_token = Security::generateRandomKey() . '_' . time();
    }

    /**
     * Removes password reset token
     */
    public function removePasswordResetToken()
    {
        $this->password_reset_token = null;
    }

    public function getName()
    {
        return Yii::$app->user->identity->name;
    }
}

backend/controllers/UsersController.php
<?php

namespace backend\controllers;

use Yii;
use backend\models\Users;
use app\models\User;
use yii\grid\GridView;
use yii\helpers\Html;

use backend\models\UsersSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use fedemotta\datatables\DataTables;
use yii\web\UploadedFile;

/**
 * UsersController implements the CRUD actions for User model.
 */
class UsersController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'delete' => ['POST'],
                ],
            ],
        ];
    }

    /**
     * Lists all User models.
     * @return mixed
     */
    public function beforeAction($action) 
    { 
        $this->enableCsrfValidation = false; 
        return parent::beforeAction($action); 
    }


 public function actionSubscriptionEnd()
    {

         $searchModel = new UsersSearch();
        // $status="";
        $dataProvider = $searchModel->search_subscription_end(Yii::$app->request->queryParams);
        // $model=new Users();
        // $model->scenario = Users::SCENARIO_REPORT;

        return $this->render('subscription_end_users', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            
        ]);
        

    }



    public function actionIndex()
    {
        $searchModel = new UsersSearch();
        $status="";
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,$status,2);
        $model=new Users();
        $model->scenario = Users::SCENARIO_REPORT;

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'model' => $model,
            'flag' => 2
        ]);
        
    }
    public function actionUserslist()
    {
        $searchModel = new UsersSearch();
        $status="";
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams,$status,0);
        $model=new Users();
        $model->scenario = Users::SCENARIO_REPORT;

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
            'model' => $model,
            'flag' => 1
        ]);
        
    }

    /**
     * Displays a single User model.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionView($id)
    {
        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new User model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
   

    /**
     * Updates an existing User model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    

    /**
     * Deletes an existing User model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     * @throws NotFoundHttpException if the model cannot be found
     */
    public function actionDelete($id)
    {
        $this->findModel($id)->delete();

        return $this->redirect(['index']);
    }

    /**
     * Finds the User model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return User the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Users::findOne($id)) !== null) {
            return $model;
        }

        throw new NotFoundHttpException('The requested page does not exist.');
    }

   
    public function actionChangestatus($id,$flag)
    {
        $success=Yii::$app->db->createCommand()
                    ->update('user', [
                    'status'=>$flag
                    ],'id = '. $id)->execute();
 
        return $this->redirect(['index']);

    }
    public function actionUnblock($id,$flag)
    {
        $success=Yii::$app->db->createCommand()
                    ->update('user', [
                    'status'=>1
                    ],'id = '. $id)->execute();
        return $this->redirect(['index']);

    }

    public function actionGetcompanywiselisting( $status)
    {
        $searchModel = new UsersSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams, $status);
        $data="";
        echo  DataTables::widget([
                  'dataProvider' => $dataProvider,
                  'id'=>'result',
                  'clientOptions' => [
                      'lengthMenu' => [200],
                      'responsive' => true, 
                      'dom' => 'BfTrtip',
                      'buttons' => [
                        'csv','excel', 'pdf', 'print'
                        ]
                    ],
                  'columns' => [
                     // ['class' => 'yii\grid\SerialColumn'],
                        'customer_id',
                        [
                            'attribute' => 'fullname',
                            'value' => function($data) { return $data->first_name  ." ". $data->last_name; }
                        ],
                        'username',
                        'email',
                        'mobile',
                        'city',
                        // [
                        //     'attribute' => 'birth_date',
                        //     'value' => function ($model) { 
                        //           return ($model->birth_date!="0000-00-00")?date_format(date_create($model->birth_date),'d-m-Y'):"";
                        //     },
                        // ],
                        [
                            'header' => 'Last Visit Date',
                            'format'=> 'raw',
                            'value' => function ($model) { 
                                   return $this->getLastVisit($model->id);
                            },
                        ], 
                        [
                            'attribute' => 'created_at',
                            'format'=> 'raw',
                            'header' => 'Registration Date',
                            'value' => function ($model) { 
                                return ($model->created_at!=NULL && $model->created_at!="0000-00-00")?"<span style='display:none'>".date_format(date_create($model->created_at),'dmYHis')."</span>".date_format(date_create($model ->created_at),'d-m-Y  H:i:s'):"-";
                            },
                        ], 
                        
                        [
                            'label'=> '#',
                            'format'=> 'raw',
                            'value' => function($model) { 
                                 return  ($model->status == 1)?Html::a('<i class="fa fa-times-circle"></i>', ['users/changestatus?id='.$model->id.'&flag=2'],array('style'=>'padding:2px 10px','class'=>'btn btn-danger','data-confirm'=>'Are you sure you want to deactivate this user?')):Html::a('<i class="fa fa-check"></i>', ['users/changestatus?id='.$model->id.'&flag=1'],array('style'=>'padding:2px 10px','class'=>'btn btn-success','data-confirm'=>'Are you sure you want to activate this user?'));
                            }
                        ],
                    ],
              ]).'<script>jQuery(function ($) {
$("#datatables_result").DataTable();
});</script> ';

    }

    public function actionGetstatuswiselisting()
    {
        if($_POST)
        {
            $status=$_POST['status'];

            $data=$this->actionGetcompanywiselisting($status);
           // echo $data;
        }
    }

    
    public function showbtn($status, $id)
    {
        if($status==1)
            return Html::a('Inactive', ['users/changestatus?id='.$id.'&flag=2'],array('class'=>'btn btn-danger','data-confirm'=>'Are you sure you want to block this user?'));
        else if($status==2)
            return Html::a('Active', ['users/changestatus?id='.$id.'&flag=1'],array('class'=>'btn btn-green','data-confirm'=>'Are you sure you want to activate this user?'));
        else
            return "";
    }

    public function getLastVisit($id)
    {
        $login = \app\models\LoginDetails::find()->where(['login_user_id' => $id])->orderBy(['login_detail_id'=>SORT_DESC])->one();
        return (!empty($login))?"<span style='display:none'>".date_format(date_create($login->login_at),'dmYHis')."</span>".date_format(date_create($login->login_at),'d-m-Y  H:i:s'):"-";
    }

    public function actionCreate()
    {
        $model = new Users();
        $model->scenario = Users::SCENARIO_CREATE;

        if ($model->load(Yii::$app->request->post()))
             {
                if($model->user_type==2){
                    $UserCount = Yii::$app->db->createCommand('SELECT count(*) as count FROM user where MONTH(created_at)=MONTH(CURDATE()) and YEAR(created_at) = YEAR(CURDATE()) and status="1" and user_type="2"')
                   ->queryOne();
                   $UserCount = sprintf('%03d',($UserCount['count']+1)); 
                        $alphachar = array_merge(range('A', 'Z'), range('a', 'z'));
                        $upperArr = range('A', 'Z') ;                
                        $fCharYear= $upperArr[(substr( date("y"), -2,1))-1];
                        $sCharYear= $upperArr[(substr( date("y"), -1,1))-1];
                        $yearQuarter = ceil(date("n") / 3);
                        $month = ltrim(date("m"), '0'); 
                        $monthCount = $upperArr[$yearQuarter-1];

backend/views/users/_search.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model app\models\UsersSearch */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="user-search">

    <?php $form = ActiveForm::begin([
        'action' => ['index'],
        'method' => 'get',
    ]); ?>

    <?= $form->field($model, 'id') ?>

    <?= $form->field($model, 'firstname') ?>

    <?= $form->field($model, 'mobile') ?>

    <?= $form->field($model, 'email') ?>

    <?= $form->field($model, 'password') ?>

    <?php // echo $form->field($model, 'status') ?>

    <?php // echo $form->field($model, 'created_at') ?>

    <?php // echo $form->field($model, 'lastname') ?>

    <?php // echo $form->field($model, 'username') ?>

    <?php // echo $form->field($model, 'auth_key') ?>

    <div class="form-group">
        <?= Html::submitButton('Search', ['class' => 'btn btn-primary']) ?>
        <?= Html::resetButton('Reset', ['class' => 'btn btn-outline-secondary']) ?>
    </div>

    <?php ActiveForm::end(); ?>

</div>

backend/views/users/index.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\grid\GridView;
use yii\helpers\Url;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use fedemotta\datatables\DataTables;
use backend\models\Users;


/* @var $this yii\web\View */
/* @var $searchModel app\models\UsersSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Users';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="card">
    <div class="card-body">
        <div class="user-index">
            <ul class="nav nav-tabs">
        <?php if($flag==2) {
    echo "<li class='active'><a href=".\yii\helpers\Url::to(['users/index']).">Customers</a></li>
        <li ><a href=".\yii\helpers\Url::to(['users/userslist']).">Internal Users</a></li>
        <li ><a href=".\yii\helpers\Url::to(['users/subscription-end']).">Subscription End</a></li>";

        }
        else {
        echo "<li ><a href=".\yii\helpers\Url::to(['users/index']).">Customers</a></li>
        <li class='active'><a href=".\yii\helpers\Url::to(['users/userslist']).">Internal Users</a></li>
         <li><a href=".\yii\helpers\Url::to(['users/subscription-end']).">Subscription End</a></li>";
        } ?>      


                
      </ul>
            <div class="row">
                <div class="col-md-12">
                    
                    <div class="btn-group">

                        <button type="button" id="changebtntxt" class="btn btn-success" >All Users</button>
                        <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
                            <span class="caret"></span>
                            <span class="sr-only">Toggle Dropdown</span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li><a onclick='return (getstatuswise("-1"))' style='cursor:pointer'>All Users</a></li>
                            <li><a onclick='return (getstatuswise(1))' style='cursor:pointer'>Active</a></li>
                            <li><a onclick='return (getstatuswise(2))' style='cursor:pointer'>Inactive</a></li>       
                        </ul>
                        
                    </div>
                    <div class="pull-right">
                          <?= Html::a('<i class="fa fa-plus"></i>', ['create'], ['class' => 'btn btn-success', 'data-toggle'=>"tooltip", 'data-original-title'=>"Add New"]) ?>
                      </div>
                </div>
            </div>
            <div class="row mt-2-2">
                <div class="col-md-12">
                    <div id="result">
                        <?= DataTables::widget([
                          'dataProvider' => $dataProvider,
                          'clientOptions' => [
                              'lengthMenu' => [200],
                              'responsive' => true, 
                              'dom' => 'BfTrtip',
                              'buttons' => [
                                'csv','excel', 'pdf', 'print'
                                ]
                            ],
                            'columns' => [
                                ['class' => 'yii\grid\SerialColumn'], 
                                'customer_id',
                                
                                [
                                    'attribute' => 'fullname',
                                    'value' => function($data) { return $data->first_name  ." ". $data->last_name; }
                                ],
                                'username',
                                //'email',
                                'mobile',
                                'city', 
                                    /*[
                                     'attribute' => 'user_type',
                                   // 'filter'=>ArrayHelper::map(Users::getUsertype(), 'role_id', 'role_name'), 
                                    'value' => 'usertype.role_name'
                                    ], */                               /*[
                                    'header' => 'Last Visit Date',
                                    'format'=> 'raw',
                                    'value' => function ($model) { 
                                        return getLastVisit($model->id);
                                    },
                                ],*/
                                /*[
                                    'header' => 'Last Visit Date',
                                    'format'=> 'raw',
                                    'value' => function ($model) { 
                                        return getLastVisit($model->id);
                                    },
                                ],*/
                                [
                                    'attribute' => 'created_at',
                                    'format'=> 'raw',
                                    'header' => 'Registration Date',
                                    'value' => function ($model) { 
                                       
                                        return ($model->created_at!=NULL && $model->created_at!="0000-00-00")?/*"<span style='display:none'>".date_format(date_create($model->created_at),'dmYHis')."</span>".*/date_format(date_create($model ->created_at),'d-m-Y'):"-";
                                    },
                                ],
                                [
                                    'label'=> '#',
                                    'format'=> 'raw',
                                    'value' => function($model) { 
                                         return  ($model->status == 1)?Html::a('<i class="fa fa-times-circle"></i>', ['users/changestatus?id='.$model->id.'&flag=2'],array('style'=>'padding:2px 10px','class'=>'btn btn-danger','data-confirm'=>'Are you sure you want to deactivate this user?')):Html::a('<i class="fa fa-check"></i>', ['users/changestatus?id='.$model->id.'&flag=1'],array('style'=>'padding:2px 10px','class'=>'btn btn-success','data-confirm'=>'Are you sure you want to activate this user?'));
                                    }
                                ],

                               
                         ['class' => 'yii\grid\ActionColumn', 'template'=> '{update} {view}',
                                'visibleButtons' => [
                                   'update' => \Yii::$app->Permission->getAccessPermission(Yii::$app->controller->id,'update'),

                                  'view' => \Yii::$app->Permission->getAccessPermission(Yii::$app->controller->id,'view'),
                                  
                                //  'delete' => \Yii::$app->Permission->getAccessPermission(Yii::$app->controller->id,'delete'),
                                  
                             ],
                            
                            ],

                            ],
                      ]);?>
                    
                    </div>
                    <div id="resultdata" style="display:none">
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<input type="hidden" id="status" value="-1"/>
<?php
function getLastVisit($id)
{
    $login = \app\models\LoginDetails::find()->where(['login_user_id' => $id])->orderBy(['login_detail_id'=>SORT_DESC])->one();
    return (!empty($login))?"<span style='display:none'>".date_format(date_create($login->login_at),'dmYHis')."</span>".date_format(date_create($login->login_at),'d-m-Y  H:i:s'):"-";
}
?>

<script type="text/javascript">
    
function getstatuswise(flag)
{
    var status="";
    if(flag==1)
        status="Active";
    else if(flag==2)
        status="Inactive";
    else
        status="All Users";
    $("#status").val(flag);
   
    $("#changebtntxt").text(status);
        $.ajax({
            type:'POST',
            url:"<?php echo Url::to(['users/getstatuswiselisting']) ?>",
            data:{'status':flag},
            success:function(items)
            {
                //alert(items);
                $("#result").hide();
                $("#resultdata").show();
                $("#resultdata").html(items);
            }
        });
}
</script>

backend/views/users/subscription_end_users.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\grid\GridView;
use yii\helpers\Url;
use kartik\select2\Select2;
use yii\helpers\ArrayHelper;
use fedemotta\datatables\DataTables;
use backend\models\Users;


/* @var $this yii\web\View */
/* @var $searchModel app\models\UsersSearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Users: Subscription End';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="card">
    <div class="card-body">
        <div class="user-index">
            <ul class="nav nav-tabs">
       <?php echo"
   <li ><a href=".\yii\helpers\Url::to(['users/index']).">Customers</a></li>
        <li ><a href=".\yii\helpers\Url::to(['users/userslist']).">Internal Users</a></li>
        <li class='active'><a href=".\yii\helpers\Url::to(['users/subscription-end']).">Subscription End</a></li>";

            ?>


                
      </ul>
            <div class="row">
                <div class="col-md-12">
                    
                    <div class="btn-group">

                        <button type="button" id="changebtntxt" class="btn btn-success" >All Users</button>
                        <button type="button" class="btn btn-success dropdown-toggle" data-toggle="dropdown">
                            <span class="caret"></span>
                            <span class="sr-only">Toggle Dropdown</span>
                        </button>
                        <ul class="dropdown-menu" role="menu">
                            <li><a onclick='return (getstatuswise("-1"))' style='cursor:pointer'>All Users</a></li>
                            <li><a onclick='return (getstatuswise(1))' style='cursor:pointer'>Active</a></li>
                            <li><a onclick='return (getstatuswise(2))' style='cursor:pointer'>Inactive</a></li>       
                        </ul>
                        
                    </div>
                    <div class="pull-right">
                          <?= Html::a('<i class="fa fa-plus"></i>', ['create'], ['class' => 'btn btn-success', 'data-toggle'=>"tooltip", 'data-original-title'=>"Add New"]) ?>
                      </div>
                </div>
            </div>
            <div class="row mt-2-2">
                <div class="col-md-12">
                    <div id="result">
                        <?= DataTables::widget([
                          'dataProvider' => $dataProvider,
                          'clientOptions' => [
                              'lengthMenu' => [200],
                              'responsive' => true, 
                              'dom' => 'BfTrtip',
                              'buttons' => [
                                'csv','excel', 'pdf', 'print'
                                ]
                            ],
                            'columns' => [
                                ['class' => 'yii\grid\SerialColumn'], 
                                'customer_id',
                                
                                [
                                    'attribute' => 'fullname',
                                    'value' => function($data) { return $data->first_name  ." ". $data->last_name; }
                                ],
                                'username',
                                //'email',
                                'mobile',
                                'city', 
                                    /*[
                                     'attribute' => 'user_type',
                                   // 'filter'=>ArrayHelper::map(Users::getUsertype(), 'role_id', 'role_name'), 
                                    'value' => 'usertype.role_name'
                                    ], */                               /*[
                                    'header' => 'Last Visit Date',
                                    'format'=> 'raw',
                                    'value' => function ($model) { 
                                        return getLastVisit($model->id);
                                    },
                                ],*/
                                /*[
                                    'header' => 'Last Visit Date',
                                    'format'=> 'raw',
                                    'value' => function ($model) { 
                                        return getLastVisit($model->id);
                                    },
                                ],*/
                                [
                                    'attribute' => 'created_at',
                                    'format'=> 'raw',
                                    'header' => 'Registration Date',
                                    'value' => function ($model) { 
                                       
                                        return ($model->created_at!=NULL && $model->created_at!="0000-00-00")?/*"<span style='display:none'>".date_format(date_create($model->created_at),'dmYHis')."</span>".*/date_format(date_create($model ->created_at),'d-m-Y'):"-";
                                    },
                                ],
                                [
                                    'label'=> '#',
                                    'format'=> 'raw',
                                    'value' => function($model) { 
                                         return  ($model->status == 1)?Html::a('<i class="fa fa-times-circle"></i>', ['users/changestatus?id='.$model->id.'&flag=2'],array('style'=>'padding:2px 10px','class'=>'btn btn-danger','data-confirm'=>'Are you sure you want to deactivate this user?')):Html::a('<i class="fa fa-check"></i>', ['users/changestatus?id='.$model->id.'&flag=1'],array('style'=>'padding:2px 10px','class'=>'btn btn-success','data-confirm'=>'Are you sure you want to activate this user?'));
                                    }
                                ],

                               
                         ['class' => 'yii\grid\ActionColumn', 'template'=> '{update} {view}',
                                'visibleButtons' => [
                                   'update' => \Yii::$app->Permission->getAccessPermission(Yii::$app->controller->id,'update'),

                                  'view' => \Yii::$app->Permission->getAccessPermission(Yii::$app->controller->id,'view'),
                                  
                                //  'delete' => \Yii::$app->Permission->getAccessPermission(Yii::$app->controller->id,'delete'),
                                  
                             ],
                            
                            ],

                            ],
                      ]);?>
                    
                    </div>
                    <div id="resultdata" style="display:none">
                    </div>
                </div>
            </div>

        </div>
    </div>
</div>
<input type="hidden" id="status" value="-1"/>
<?php
function getLastVisit($id)
{
    $login = \app\models\LoginDetails::find()->where(['login_user_id' => $id])->orderBy(['login_detail_id'=>SORT_DESC])->one();
    return (!empty($login))?"<span style='display:none'>".date_format(date_create($login->login_at),'dmYHis')."</span>".date_format(date_create($login->login_at),'d-m-Y  H:i:s'):"-";
}
?>

<script type="text/javascript">
    
function getstatuswise(flag)
{
    var status="";
    if(flag==1)
        status="Active";
    else if(flag==2)
        status="Inactive";
    else
        status="All Users";
    $("#status").val(flag);
   
    $("#changebtntxt").text(status);
        $.ajax({
            type:'POST',
            url:"<?php echo Url::to(['users/getstatuswiselisting']) ?>",
            data:{'status':flag},
            success:function(items)
            {
                //alert(items);
                $("#result").hide();
                $("#resultdata").show();
                $("#resultdata").html(items);
            }
        });
}
</script>