frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use frontend\models\ResendVerificationEmailForm;
use frontend\models\VerifyEmailForm;
use Yii;
use yii\base\InvalidArgumentException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\web\session;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use app\models\PasswordForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use yii\db\Query;
use yii\helpers\Json;
use yii\web\Response;
use yii\helpers\Url;
use app\models\User;
// use PHPMailer\PHPMailer\PHPMailer;
// use PHPMailer\PHPMailer\Exception;
/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    

                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function beforeAction($action) {
        $this->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }

    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $model=\backend\models\HomeBlocks::find()->orderBy(['id'=> SORT_DESC])->one();
        return $this->render('index',['model' => $model]);
    }
    
    
         public function actionSubscriptionRequest()
      {
      
     
      //print_r(Yii::$app->user->id);die;
      //echo $effectiveDate;die;
      if (Yii::$app->request->post() )
      {
        //print_r($_POST);die;
        $model=new \backend\models\Orders();

         
          $model->first_name=$_POST['firstname'];
          $model->last_name=$_POST['lastname'];
          $model->email=$_POST['email'];
          $model->phone=$_POST['phone'];
           $model->city=$_POST['city'];
           $model->amount=$_POST['amount'];
           $model->user_id=0;
           $model->created_date=date('Y-m-d H:i:s');
             $model->payment_status='0';
          $str=$_POST['subcription_id'];



          $subcription_id = (int) filter_var($str, FILTER_SANITIZE_NUMBER_INT);

      $model->subcription_id=$subcription_id;


       $sub = \backend\models\Subscriptions::find()->where(['id'=>$model->subcription_id])->one();
            //print_r($model);die;

            if($sub->one_month== $model->amount)
            {
               $model->subcription_plan=1;
            }else if($sub->twelve_month==$model->amount)
            {
                $model->subcription_plan=12;

            }else
            {
               $model->subcription_plan=3;

            }
     // echo $model->subcription_plan;die;

      $effectiveDate = date('Y-m-d H:i:s', strtotime("+".$model->subcription_plan." months", strtotime($model->created_date)));
            //echo "$effectiveDate";die;
      $model->payment_start_date=$model->created_date;
      $model->payment_end_date=$effectiveDate;
          //echo $int;die;
           $model->save(false);

           return $this->render('thankyou');

        
      } 

      return $this->render('subcription_request');
      }




    
    public function actionSuccess()
    {
      
        
            return $this->render('success');
         
    }
   
   public function actionFailure()
    {

      return $this->render('failure');
    }

    public function actionSubscription()
{
$subscription=\backend\models\Subscriptions::find()->where(['status'=>1])->orderBy(['script_per_week'=> SORT_ASC])->all();
$model=\backend\models\Services::find()->orderBy(['id'=> SORT_DESC])->one();

  // if (Yii::$app->request->post()) {
  //  // $one=$_POST['subscription']['1_month'];
  //  // $two=$_POST['subscription']['2_month'];
  //  // $two=$_POST['subscription']['2_month'];
    

  // }

return $this->render('subscription',['model' => $model,'subscription'=>$subscription]);

}

 

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        $login = new \app\models\LoginDetails();

        if ($model->load(Yii::$app->request->post())) {
          $log = \app\models\User::find()->where(['username' => $_POST['LoginForm']['username'], 'status' => 1, 'user_type'=>2])->one();
           // print_r($_POST['LoginForm']['username']);die;
            if(empty($log)) {
                 \Yii::$app->session->setFlash('error', '<i class="fa fa-warning"></i><b> Incorrect username or password. !</b>');
                return $this->render('login', ['model' => $model]);
            }
            $login->login_user_id = $log['id'];
            $login->login_status = 1;
            $login->login_at = new \yii\db\Expression('NOW()');
            $login->user_ip_address=$_SERVER['REMOTE_ADDR'];
            $login->save(false);
            if($log->password===sha1($model->password))
            {
                $otp = random_int(1000, 9999);
                $log->otp = $otp;
                $log->save();
                
                require '../../vendor/autoload.php'; 
                    $email = new \SendGrid\Mail\Mail(); 
                    $content='<div style="font:18px/23px Arial,Helvetica,sans-serif;background:#f3f3f3">
                     <div style="max-width:800px;margin-left:auto;margin-right:auto">
                        <div style="width:640px;margin-left:auto;margin-right:auto;padding:20px 0px 20px 0px; style="text-align: center;">
                            <table class="x_-665217761MsoNormalTable" border="1" cellspacing="3" cellpadding="0" style="border: solid rgb(204,204,204) 1.0pt;background: #fff;color: #000;width:98%">
                          <tbody>
                            <tr>
                              <td style="border: none;padding: 2pt 22.5pt 2pt 22.5pt;">
                              <h2 align="center" style="text-align: center;font-family: Helvetica;">Welcome to vishwaswealthadvisory.com</h2>
                              <p class="MsoNormal" align="center" style="text-align: center;font-family: Helvetica;"><span style="font-size: 10.0pt;">You are all set now.</span></p>
                              </td>
                            </tr>
                           
                            <tr>
                              <td style="border: none;padding: 2pt 22.5pt 2pt 22.5pt;">
                               <p class="MsoNormal" align="center" style="text-align: center;font-family: Helvetica;"><span style="font-size: 10.0pt;">Use the following OTP to complete your Login procedures.</p>
                              </td>
                            </tr>
                             <tr>
                              <td style="border: none;padding: 2pt 22.5pt 2pt 22.5pt;">
                               <p class="MsoNormal" align="center" style="text-align: center;font-family: Helvetica;"><span style="font-size: 10.0pt;"><b>OTP - </b>'.$otp.'<b></p>
                              </td>
                            </tr>
                              <tr>
                              <td style="border: none;padding: 5pt 22.5pt 5pt 22.5pt;">
                               <p class="MsoNormal" align="center" style="text-align: center;font-family: Helvetica;"><span style="font-size: 10.0pt;">Thank You</span></p>
                              </td>
                            </tr>
                           
                          </tbody>
                        </table> 
                        </div>
                     </div>
                  </div>';
                  $email->setFrom("info@vishwaswealthadvisory.com","Vishwas Wealth Advisory");
                $email->setSubject('Sign-in to Vishwas Wealth Advisory' );
                $email->addTo($log->email);
                 $adminEmail = \app\models\User::find()->select('email')->where(['status' => 1, 'user_type'=>1])->one();
                if($adminEmail->email!="")
                 $email->addCc($adminEmail->email);
                $email->addContent(
                    "text/html", $content
                );
                $sendgrid = new \SendGrid(Yii::$app->params['SENDGRID_API_KEY']);
                try {
                    $response = $sendgrid->send($email);
                    // $response= $response->statusCode() . "\n";
                    // $response=($response->headers());
                    // $response= $response->body() . "\n";
                } catch (Exception $e) {
                    $response= 'Caught exception: '. $e->getMessage() ."\n";
                }
                return $this->redirect(['loginotp','user'=>base64_encode(json_encode($model->attributes))]);
            }
            else{
                \Yii::$app->session->setFlash('error', '<i class="fa fa-warning"></i><b> Incorrect username or password. !</b>');

frontend/views/site/faq-bk10052021.php
<!--Page Title-->
<section class="page-title centred" style="background-image: url(<?= Yii::$app->params['basepath'];?>/images/bg/page-title-2.jpg);">
    <div class="auto-container">
        <div class="content-box clearfix">
            <h1>FAQ's</h1>
           
        </div>
    </div>
</section>
<!--End Page Title-->
<!-- service-section -->

<section class="service-section pb-50">
  
    <div class="auto-container">
        <div class="blog-details-content">
            <div class="comments-area">
               <div class="comment-box">
                    <div class="comment" style="padding-left:0">
                        <div class="comment-inner">
                            <div class="comment-info clearfix">
                                <div class="name pull-left">
                                    <h5>Why isn’t the Purchase Price (PP) advised on weekdays?</h5>
                                </div>
                            </div>
                            <div class="text">
                                <p>Our proprietary algorithm is based on the weekly behaviour of stock prices, which is computed at market closing and emailed on Sunday mornings.</p>
                            </div>
                        </div>
                    </div>
                    <div class="comment" style="padding-left:0">
                        <div class="comment-inner">
                            <div class="comment-info clearfix">
                                <div class="name pull-left">
                                    <h5>How many units do I purchase on a subsequent purchase? i.e. 2nd, 3rd, etc.?</h5>
                                </div>
                            </div>
                            <div class="text">
                                <p>We recommend purchasing an equal or a greater number of units on a subsequent purchase. Purchasing lesser units on a subsequent purchase deviates you from the targeted goal. Paid subscribers who update their purchases on our portal, can track changes in their targeted sell price.</p>
                            </div>
                        </div>
                    </div>
                    <div class="comment" style="padding-left:0">
                        <div class="comment-inner">
                            <div class="comment-info clearfix">
                                <div class="name pull-left">
                                    <h5>What if I couldn’t make transactions as advice by VWA?</h5>
                                </div>
                            </div>
                            <div class="text">
                                <p>We understand that life isn’t always fair! Hence, our portal is built keeping such uncertainties in mind, even if you deviate from the advice, but have an updated transaction history on the portal; you would have a custom solution ready. In case you’re unsure of your transaction frequency, we recommend upgrading to a premium account.</p>
                            </div>
                        </div>
                    </div>
                    <div class="comment" style="padding-left:0">
                        <div class="comment-inner">
                            <div class="comment-info clearfix">
                                <div class="name pull-left">
                                    <h5>How are the returns calculated?</h5>
                                </div>
                            </div>
                            <div class="text">
                                <p>Our proprietary algorithm has similarities with a banking method, wherein rupee weeks of investment are computed to calculate annual returns using simple arithmetic of gains.</p>
                            </div>
                        </div>
                    </div>
                    <div class="comment" style="padding-left:0">
                        <div class="comment-inner">
                            <div class="comment-info clearfix">
                                <div class="name pull-left">
                                    <h5>What if I have an appetite for more transactions than what’s recommended in VWA’s weekly advisory?</h5>
                                </div>
                            </div>
                            <div class="text">
                                <p>Our premium plan is designed keeping in mind an urban, retail investor. If you intend to make more transactions each month, we have an add-on plan for you as well.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
           
        </div>
    </div>
</section>

frontend/views/site/left.php
<div class="fxt-bg-img" data-bg-image="<?= Yii::$app->params['basepath'];?>images/login-bg.jpg" style="background-image: url(<?= Yii::$app->params['basepath'];?>images/login-bg.jpg);">
    <div class="fxt-header">
      <div class="fxt-transformY-50 fxt-transition-delay-1">
        <a href="#" class="fxt-logo"><img src="<?= Yii::$app->params['logo'];?>" alt="Logo"></a>
      </div>
      <div class="fxt-transformY-50 fxt-transition-delay-2">
        <h1>Welcome to Kalcy</h1>
      </div>
      <div class="fxt-transformY-50 fxt-transition-delay-3">
        <p>Kalcy Business solutions Pvt. Ltd. originated with the idea of providing all types of accounting services under one roof that would make clients feel safe and find refuge. We strongly believe that every number counts…</p>
      </div>
    </div>
    <ul class="fxt-socials">
      <li class="fxt-facebook fxt-transformY-50 fxt-transition-delay-4"><a href="https://www.facebook.com/kalcy.Business" title="Facebook" target="_blank"><i class="fa fa-facebook"></i></a></li>
      <li class="fxt-twitter fxt-transformY-50 fxt-transition-delay-5"><a href="#" title="twitter"><i class="fa fa-twitter"></i></a></li>
      <li class="fxt-google fxt-transformY-50 fxt-transition-delay-6"><a href="https://www.instagram.com/kalcy_business_solution/" title="instagram" target="_blank"><i class="fa fa-instagram"></i></a></li>
      <li class="fxt-linkedin fxt-transformY-50 fxt-transition-delay-7"><a href="https://www.linkedin.com/in/kalcy-business-solutions-0580901b6/" title="linkedin" target="_blank"><i class="fa fa-linkedin"></i></a></li>
      <!-- <li class="fxt-youtube fxt-transformY-50 fxt-transition-delay-8"><a href="#" title="youtube"><i class="fa fa-youtube"></i></a></li> -->
    </ul>
</div>

frontend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */
//https://affixtheme.com/html/xmee/demo/register-4.html
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use kartik\date\DatePicker;

?>

<div class="site-login">
  <main id="page-main" role="main">
    <section class="contact-section" style="background-image: url(<?= Yii::$app->params['basepath'];?>/images/contact-1.jpg);">
        <div class="auto-container">
            <div class="row clearfix">
                <div class="col-xl-5 col-lg-5 col-md-5 col-md-offset-4 content-column">
                    <div id="content_block_nine">
                        <div class="content-box bg-color-white">
                            <div class="sec-title style-three left mb-0">
                                <h5>Log In</h5>
                            </div>
                           
                            <div class="form-inner" style="padding-top:0;">
                              <?php if (Yii::$app->session->hasFlash('success')): ?>
                                <div class="alert alert-success alert-dismissable">
                                     <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                                     <?= Yii::$app->session->getFlash('success') ?>
                                </div>
                            <?php endif; ?>

                            <?php if (Yii::$app->session->hasFlash('error')): ?>
                                <div class="alert alert-danger alert-dismissable">
                                     <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                                     <h4>Error!</h4>
                                     <?= Yii::$app->session->getFlash('error') ?>
                                </div>
                            <?php endif; ?>
                            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
                             <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <?= $form->field($model, 'username', ['template' => '
                                           <div class="row"><div class="col-md-12">{label}</div></div>
                                           <div class="row">
                                               <div class="col-sm-12">
                                                   <div class="input-group">
                                                      
                                                      {input}
                                                   </div>
                                                   {error}{hint}
                                               </div>
                                            </div>'])->textInput(['class'=>'form-control ']) ?>
                                    </div>
                                </div>
                             </div>
                              <div class="row">
                                <div class="col-md-12">
                                  <div class="form-group">
                                   <?= $form->field($model, 'password')->passwordInput(['autofocus' => true, 'class'=>'form-control']) ?>
                                   
                                            <i toggle="#password" class="fa fa-fw toggle-pwdpassword field-icon fa-eye"></i>
                                  
                                  </div>
                                </div>
                                <div class="col-md-12 text-right">
                                  <div class="form-group mb-2">
                                <a href="<?= yii\helpers\Url::to(["site/request-password-reset"])?>" class="nav-link" >Reset Your Password</a>
                                    </div>
                                </div>
                                
                              </div>
                              <div class="form-group">
                                <!-- <button type="submit" class="fxt-btn-fill">Log in</button> -->
                                <?= Html::submitButton('Login', ['class' => 'theme-btn style-three', 'name' => 'login-button']) ?>
                              </div>
                            <?php ActiveForm::end(); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
  </main>

</div>

frontend/views/site/login_otp.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */
//https://affixtheme.com/html/xmee/demo/register-4.html
use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
use kartik\date\DatePicker;

?>

<div class="site-login">
  <main id="page-main" role="main">
    <section class="contact-section" style="background-image: url(<?= Yii::$app->params['basepath'];?>/images/contact-1.jpg);">
        <div class="auto-container">
            <div class="row clearfix">
                <div class="col-xl-5 col-lg-5 col-md-5 col-md-offset-4 content-column">
                    <div id="content_block_nine">
                        <div class="content-box bg-color-white">
                            <div class="sec-title style-three left mb-0">
                                <h5>Enter OTP</h5>
                            </div>
                           
                            <div class="form-inner" style="padding-top:0;">
                              <?php if (Yii::$app->session->hasFlash('success')): ?>
                                <div class="alert alert-success alert-dismissable">
                                     <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                                     <?= Yii::$app->session->getFlash('success') ?>
                                </div>
                            <?php endif; ?>

                            <?php if (Yii::$app->session->hasFlash('error')): ?>
                                <div class="alert alert-danger alert-dismissable">
                                     <button aria-hidden="true" data-dismiss="alert" class="close" type="button">×</button>
                                     <h4>Error!</h4>
                                     <?= Yii::$app->session->getFlash('error') ?>
                                </div>
                            <?php endif; ?>
                            <?php $form = ActiveForm::begin(['id' => 'login-form']); ?>
                             <div class="row">
                                <div class="col-md-12">
                                    <div class="form-group">
                                        <?= $form->field($model, 'otp', ['template' => '
                                           <div class="row"><div class="col-md-12">{label}</div></div>
                                           <div class="row">
                                               <div class="col-sm-12">
                                                   <div class="input-group">
                                                      
                                                      {input}
                                                   </div>
                                                   {error}{hint}
                                               </div>
                                            </div>'])->textInput(['class'=>'form-control '])->label('OTP') ?>
                                    </div>
                                </div>
                             </div>
                              
                              <div class="form-group">
                                <!-- <button type="submit" class="fxt-btn-fill">Log in</button> -->
                                <?= Html::submitButton('Validate OTP', ['class' => 'theme-btn style-three', 'name' => 'login-button']) ?>
                              </div>
                            <?php ActiveForm::end(); ?>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    
  </main>

</div>

frontend/views/site/services.php
<!--Page Title-->
<?php
Yii::$app->metaTags->register($model);
 if($model->banner->banner_image!="")
            {
                 echo "<section class='page-title centred' style='background-image: url(".$model->banner->banner_image.");'>";
            }
            else
            {
                echo "<section class='page-title centred' style='background-image: url(<?= Yii::$app->params['basepath'];?>/images/bg/page-title-2.jpg);'>";
            }
         ?>
    <div class="auto-container">
        <div class="content-box clearfix">
            <h1><?php echo $model->title; ?></h1>
            <!--<ul class="bread-crumb clearfix">-->
            <!--    <li><a href="">Home</a></li>-->
            <!--    <li>Services</li>-->
            <!--</ul>-->
        </div>
    </div>
</section>
<!--End Page Title-->
<!-- service-section -->

<section class="service-section">
    <div class="auto-container">
        <div class="sec-title centred">
            <h5>WHAT WE PROVIDE</h5>
        </div>
    </div>
    <div class="auto-container">
        <div class="sec-title centred">
           <!--  <p>You may not always have the time to curate and plan your wealth. VWA will help make your family wealth planning easier by chalking out solutions that will help you achieve your financial goals. VWA does not manage your money, your money will always be in your control. We invest experience, you invest money. An hour-and-a-half every weekend is what we want our investors to invest with us to reap maximum benefits. And once our informed investors get confident, they will better evolve to a balanced portfolio and truly paint their own masterpiece. VWA sincerely hopes to become contributors to its investor's wealth creation process.</p> -->

           <?php echo $model->body; ?>
        </div>
    </div>
</section>
<section class="service-style-five bg-color-1 pb-50 pt-50" id="content_block_four">
    <div class="auto-container content-box " >
        <div class="sec-title style-four right">
            <h5>What we offer</h5>
            <!-- <h2>Quality Services With Difference</h2> -->
        </div>
        <div class="tabs-content">
            <div class="row ulstyle">
                <?php echo $model->what_we_offer; ?>
            </div>
        </div>
    </div>
</section>
<section class="pricing-section " style="background-image: url(<?= Yii::$app->params['basepath'];?>/images/pricing-bg.jpg);">
    <div class="auto-container">
        <div class="tabs-box centred">
            <!--<div class="sec-title style-four right">-->
            <!--    <h5>What we offer</h5>-->
            <!--    <h2>Quality Services With Difference</h2>-->
            <!--</div>-->
            <div class="tabs-content">
                <div class="tab active-tab" id="tab-1">
                    <div class="row clearfix">
                        <div class="col-lg-4 col-md-6 col-sm-12 pricing-block col-md-offset-2">
                            <div class="pricing-block-one">
                                <div class="pricing-table">
                                    <div class="table-header">
                                        <h3>Free Trial</h3>
                                        <!--<div class="price-box">-->
                                            <!-- <span>recommended</span> -->
                                        <!--    <h2>Free for lifetime</h2><br/>-->
                                        <!--</div>-->
                                        <!-- <span class="text">This Plan Includes Global Relations</span> -->
                                    </div>
                                    <div class="table-content">
                                        <ul class="clearfix"> 
                                           <?php echo $model->feee_trial; ?>
                                        </ul>
                                    </div>
                                    <div class="theme-btn style-three">
                                        <a style="color:white" href="<?= \yii\helpers\Url::to(['site/signup'])?>">Signup</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="col-lg-4 col-md-6 col-sm-12 pricing-block">
                            <div class="pricing-block-one">
                                <div class="pricing-table">
                                    <div class="table-header">
                                        <h3>Premium</h3>
                                        <!--<div class="price-box">-->
                                        <!--    <span>recommended</span>-->
                                        <!--    <h2>₹ 400</h2>-->
                                        <!--    <p>/ Month</p>-->
                                        <!--</div>-->
                                    </div>
                                    <div class="table-content">
                                        <ul class="clearfix"> 
                                            <?php echo $model->premium; ?>
                                        </ul>
                                    </div>
                                    <div class="theme-btn style-three">
                                        
                                        <a style="color:white" href="<?= \yii\helpers\Url::to(['site/subscription'])?>">Subscribe</a>
                                        
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

<section class="cta-section">
        <div class="pattern-layer" style="background-image: url(<?= Yii::$app->params['basepath'];?>//images/pattern/shape-3.png);"></div>
        <div class="auto-container">
            <div class="inner-container clearfix">
                <div class="title pull-left col-md-12">
                    <h4 style="color:#fff"><?php echo $model->membership_text; ?></h4>
                </div>
                <!--<div class="btn-box pull-right col-md-4">-->
                <!--    <a href="">Signup</a>-->
                <!--    <a>Pre-book</a>-->
                <!--</div>-->
            </div>
        </div>
    </section>

</section>
   <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.7.1/jquery.min.js" type="text/javascript"></script>
<script type="text/javascript">
   $(document).ready(function(){
  
    $("li#services").addClass("current");

});
</script>

<!--  -->